name: 代码检查CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取仓库代码（基础步骤，自带，不用在列表选）
      - name: 拉取代码
        uses: actions/checkout@v4

      # 2. Setup Node.js environment 配置Node环境
      - name: 配置Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          # 指定你的package-lock.json在server文件夹
          cache-dependency-path: server/package-lock.json
